apiVersion: apps/v1
kind: Deployment
metadata:
  name: reham
spec:
  selector:
    matchLabels:
      app: sara
  replicas: 3
  template:
    metadata:
      name: my-web-pod
      labels:
        app: sara
    spec:
      containers:
        - image: rehamhany/myweb-img
          name: myimage2
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"