apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: sara   

  ports:
    - port: 8080 # Cluster IP service port
      targetPort: 80 # Pod/container port
      nodePort: 30005 # Any port between 30000 and 32767 [OPTIONAL]